version: "3"
services:
  mongodb: 
    #image: yourregistry.azurecr.io/bib/mongo:5
    image: lazynerdsacr.azurecr.io/mongo:5
    restart: always
    ports:
      - 27017:27017

  mongo-seed: #this is used to populate the DB, see dockerfile for import command
    build: 
      context: ./db-seed
      args:
        HOST: mongodb
    #image: yourregistry.azurecr.io/bib/mongo-seed:webapp
    image: lazynerdsacr.azurecr.io/mongo-seed:v1
    depends_on:
      - mongodb
          
  api:
    build:
      context: ./api
    #image: yourregistry.azurecr.io/bib/api
    image: lazynerdsacr.azurecr.io/api:v1
    depends_on:
      - mongodb
    environment:
      PORT: 4000
      # MONGO_URI: ${MONGO_URI}
      MONGO_URI: mongodb://mongodb:27017/dobook

  frontend:
    build:
      context: ./frontend
    #image: yourregistry.azurecr.io/bib/frontend
    image: lazynerdsacr.azurecr.io/frontend:v1
    depends_on:
      - api
    environment:
      API_HOST: api
      API_PORT: 4000
    ports:
      - "80:80"
