# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 'application'


    strategy:
      matrix:
        node-version: [14.x]
        project: [frontend, api]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './application/${{matrix.project}}/package-lock.json'
    - run: npm ci
      working-directory: './application/${{matrix.project}}'
    - run: npm run build --if-present
      working-directory: './application/${{matrix.project}}'
    - run: npm test
      working-directory: './application/${{matrix.project}}'

  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        shell: bash
        working-directory: 'application'
    strategy:
      matrix:
        node-version: [ 14.x ]
        project: [ frontend, api, db-seed ]
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
#      - name: Get tag
#        id: tag
#        uses: dawidd6/action-get-tag@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: log into ACR
        uses: docker/login-action@v1
        with:
          registry: ${{secrets.ACR_ENDPOINT}}
          username: ${{secrets.ACR_USERNAME}}
          password: ${{secrets.ACR_PASSWORD}}
      - name: Build & Push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest